version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args: 
        MONGO_URL: mongodb+srv://umarazadwork:Ia4x1XIoQ1ZsBNxU@devops.jyv3lli.mongodb.net/?retryWrites=true&w=majority&appName=DevOps
        SECRET_KEY: cheentakpaktmtm
    container_name: web_backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb+srv://umarazadwork:Ia4x1XIoQ1ZsBNxU@devops.jyv3lli.mongodb.net/?retryWrites=true&w=majority&appName=DevOps


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_BASE_URL: http://web_backend:5000
    container_name: web_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend