version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: web_backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb+srv://umarazadwork:Ia4x1XIoQ1ZsBNxU@devops.jyv3lli.mongodb.net/?retryWrites=true&w=majority&appName=DevOps
    volumes:
      - ./backend:/app
    networks:
      - shop-sphere-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: web_frontend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    depends_on:
      - backend
    networks:
      - shop-sphere-network

networks:
  shop-sphere-network:
    driver: bridge